const INCREMENT = "INCREMENT";
const INCREMENT_STEP = "INCREMENT_STEP";

const DECREMENT = "DECREMENT";
const DECREMENT_STEP = "DECREMENT_STEP";

module.exports = { INCREMENT, INCREMENT_STEP, DECREMENT, DECREMENT_STEP };
